package org.example.file;

public enum ErrorType {
    INVALID_ARGUMENT_COUNT,
    FILE_NAME_EMPTY,
    FILE_NAME_INVALID_CHARS,
    FILE_PATH_INVALID_SYNTAX,
    FILE_ALREADY_EXISTS,
    LINE_COUNT_NOT_A_NUMBER,
    LINE_COUNT_NOT_POSITIVE,
    DIRECTORY_NOT_WRITABLE,
    LINE_COUNT_IS_NULL
}