package org.example.file.validation;

public enum ErrorType {
    FILE_NAME_EMPTY,
    FILE_NAME_INVALID_CHARS,
    FILE_PATH_INVALID_SYNTAX,
    DIRECTORY_NOT_WRITABLE,
    INPUT_FILE_NOT_FOUND,
    INPUT_PATH_IS_DIRECTORY,
    INPUT_FILE_NOT_READABLE,
    OUTPUT_DIRECTORY_NOT_CREATABLE,
    OUTPUT_PATH_IS_NOT_DIRECTORY
}